<?php

namespace Simounet\RemindMeBundle\Repository;

/**
 * EntriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntriesRepository extends \Doctrine\ORM\EntityRepository
{
}
