simounet_remindme_homepage:
    path:     /
    defaults: { _controller: SimounetRemindMeBundle:Default:index }

simounet_remindme_entry_add:
    path:     /add
    defaults: { _controller: SimounetRemindMeBundle:Entry:add }
